# Generated by Django 5.0.4 on 2024-04-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipe',
            name='receipe_image',
            field=models.ImageField(null=True, upload_to='receipe'),
        ),
    ]
